dataset:
  name: ODE_Lorenz

model:
  name: reservoir
  seed: 0
  res_dim: 2000
  leak_rate: 0.6
  bias: 1.6
  embedding_scaling: 0.08
  Wr_density: 0.02
  Wr_spectral_radius: 0.8
  chunks: 1
  locality: 0
  beta: 8e-8
  data_dim: 3
  spinup: 15