dataset:
  name: PDE_KS
  
model:
  name: reservoir
  seed: 0
  res_dim: 2000
  leak_rate: 1
  bias: 0
  embedding_scaling: 1.0
  Wr_density: 0.02
  Wr_spectral_radius: 0.6
  chunks: 64
  locality: 2
  beta: 8e-8
  data_dim: 1024
  spinup: 10