dataset:
  name: PDE_KS
  pair_id:
  - 6
model:
  Wr_density: 0.02
  Wr_spectral_radius: 0.7684148525149019
  beta: 0.01260076676549322
  bias: 0
  chunks: 64
  data_dim: 1024
  embedding_scaling: 0.39418029612121486
  leak_rate: 1
  locality: 8
  name: reservoir
  res_dim: 822
  seed: 0
  spinup: 15
