dataset:
  name: PDE_KS
  pair_id:
  - 3
model:
  Wr_density: 0.02
  Wr_spectral_radius: 0.17311439185121744
  beta: 5.5021758174510244e-09
  bias: 0
  chunks: 16
  data_dim: 1024
  embedding_scaling: 0.012667814216644252
  leak_rate: 1
  locality: 1
  name: reservoir
  res_dim: 1985
  seed: 0
  spinup: 100
