dataset:
  name: PDE_KS
  pair_id:
  - 1
model:
  Wr_density: 0.02
  Wr_spectral_radius: 0.13666351729528683
  beta: 1.1171628177116457e-08
  bias: 0
  chunks: 64
  data_dim: 1024
  embedding_scaling: 0.001356818914492271
  leak_rate: 1
  locality: 6
  name: reservoir
  res_dim: 825
  seed: 0
  spinup: 100
