dataset:
  name: Lorenz_Official
  pair_id:
  - 6
hyperparameters:
  leak_rate:
    lower_bound: 0
    type: uniform
    upper_bound: 1
  bias:
    lower_bound: 0
    type: uniform
    upper_bound: 2
  embedding_scaling:
    lower_bound: 0.0001
    type: loguniform
    upper_bound: 1.0
  Wr_spectral_radius:
    lower_bound: 0.02
    type: uniform
    upper_bound: 1.0
  beta:
    lower_bound: 0.0000000001
    type: loguniform
    upper_bound: 0.1
  res_dim: 
    lower_bound: 500
    type: randint
    upper_bound: 3000
model:
  name: reservoir
  chunks: 1
  locality: 0
  seed: 0
  data_dim: 3
  spinup: 15
  Wr_density: 0.02
  train_split: 0.8